<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use App\Models\StandardReferenceRange;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $references = [
            // 1. POTÁSSIO - Simple (applies to all)
            [
                'parameter_code' => 'POTASSIO',
                'parameter_name' => 'Potássio',
                'gender' => 'both',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => 3.5,
                'reference_max' => 5.5,
                'unit' => 'mEq/L',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => null,
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 2. CREATININA - By age
            [
                'parameter_code' => 'CREAT',
                'parameter_name' => 'Creatinina',
                'gender' => 'both',
                'age_min' => 18,
                'age_max' => 90,
                'reference_min' => 0.70,
                'reference_max' => 1.30,
                'unit' => 'mg/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => '18 a 90 anos',
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 3. ÁCIDO ÚRICO - By gender
            [
                'parameter_code' => 'AC_URICO',
                'parameter_name' => 'Ácido Úrico',
                'gender' => 'male',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => 3.5,
                'reference_max' => 7.2,
                'unit' => 'mg/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => 'Homem',
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],
            [
                'parameter_code' => 'AC_URICO',
                'parameter_name' => 'Ácido Úrico',
                'gender' => 'female',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => 2.4,
                'reference_max' => 6.0,
                'unit' => 'mg/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => 'Mulher',
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 4. FERRO - By gender
            [
                'parameter_code' => 'FERRO',
                'parameter_name' => 'Ferro',
                'gender' => 'male',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => 70.0,
                'reference_max' => 180.0,
                'unit' => 'µg/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => 'Homem',
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],
            [
                'parameter_code' => 'FERRO',
                'parameter_name' => 'Ferro',
                'gender' => 'female',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => 60.0,
                'reference_max' => 180.0,
                'unit' => 'µg/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => 'Mulher',
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 5. TESTOSTERONA TOTAL - By gender + age
            [
                'parameter_code' => 'TEST_TOTAL',
                'parameter_name' => 'Testosterona Total',
                'gender' => 'male',
                'age_min' => 18,
                'age_max' => 66,
                'reference_min' => 175.00,
                'reference_max' => 781.00,
                'unit' => 'ng/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => 'Homens 18 a 66 anos',
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],
            [
                'parameter_code' => 'TEST_TOTAL',
                'parameter_name' => 'Testosterona Total',
                'gender' => 'female',
                'age_min' => 21,
                'age_max' => 73,
                'reference_min' => 10.00,
                'reference_max' => 75.00,
                'unit' => 'ng/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => 'Mulheres 21 a 73 anos',
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 6. COLESTEROL TOTAL - Categorical
            [
                'parameter_code' => 'COL_TOTAL',
                'parameter_name' => 'Colesterol Total',
                'gender' => 'both',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => null,
                'reference_max' => null,
                'unit' => 'mg/dL',
                'reference_type' => 'categorical',
                'reference_categories' => json_encode([
                    ['name' => 'Desejável', 'min' => null, 'max' => 200],
                    ['name' => 'Limítrofe', 'min' => 200, 'max' => 239],
                    ['name' => 'Alto', 'min' => 240, 'max' => null],
                ]),
                'condition' => null,
                'description' => null,
                'source' => 'NCEP ATP III',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 7. COLESTEROL LDL - Categorical
            [
                'parameter_code' => 'LDL',
                'parameter_name' => 'Colesterol LDL',
                'gender' => 'both',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => null,
                'reference_max' => null,
                'unit' => 'mg/dL',
                'reference_type' => 'categorical',
                'reference_categories' => json_encode([
                    ['name' => 'Ótimo', 'min' => null, 'max' => 100],
                    ['name' => 'Desejável', 'min' => 100, 'max' => 129],
                    ['name' => 'Limítrofe', 'min' => 130, 'max' => 159],
                    ['name' => 'Alto', 'min' => 160, 'max' => 189],
                    ['name' => 'Muito Alto', 'min' => 190, 'max' => null],
                ]),
                'condition' => null,
                'description' => null,
                'source' => 'NCEP ATP III',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 8. COLESTEROL HDL - Categorical by gender
            [
                'parameter_code' => 'HDL',
                'parameter_name' => 'Colesterol HDL',
                'gender' => 'male',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => null,
                'reference_max' => null,
                'unit' => 'mg/dL',
                'reference_type' => 'categorical',
                'reference_categories' => json_encode([
                    ['name' => 'Baixo', 'min' => null, 'max' => 40],
                    ['name' => 'Desejável', 'min' => 40, 'max' => null],
                ]),
                'condition' => null,
                'description' => 'Homem',
                'source' => 'NCEP ATP III',
                'laboratory_id' => null,
                'active' => true,
            ],
            [
                'parameter_code' => 'HDL',
                'parameter_name' => 'Colesterol HDL',
                'gender' => 'female',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => null,
                'reference_max' => null,
                'unit' => 'mg/dL',
                'reference_type' => 'categorical',
                'reference_categories' => json_encode([
                    ['name' => 'Baixo', 'min' => null, 'max' => 50],
                    ['name' => 'Desejável', 'min' => 50, 'max' => null],
                ]),
                'condition' => null,
                'description' => 'Mulher',
                'source' => 'NCEP ATP III',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 9. TRIGLICÉRIDES - Categorical
            [
                'parameter_code' => 'TRIG',
                'parameter_name' => 'Triglicérides',
                'gender' => 'both',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => null,
                'reference_max' => null,
                'unit' => 'mg/dL',
                'reference_type' => 'categorical',
                'reference_categories' => json_encode([
                    ['name' => 'Desejável', 'min' => null, 'max' => 150],
                    ['name' => 'Limítrofe', 'min' => 150, 'max' => 199],
                    ['name' => 'Alto', 'min' => 200, 'max' => 499],
                    ['name' => 'Muito Alto', 'min' => 500, 'max' => null],
                ]),
                'condition' => null,
                'description' => null,
                'source' => 'NCEP ATP III',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 10. GLICOSE - By condition (jejum/sem jejum)
            [
                'parameter_code' => 'GLICOSE',
                'parameter_name' => 'Glicose',
                'gender' => 'both',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => 70.0,
                'reference_max' => 99.0,
                'unit' => 'mg/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => 'jejum',
                'description' => 'Em jejum',
                'source' => 'SBD',
                'laboratory_id' => null,
                'active' => true,
            ],
            [
                'parameter_code' => 'GLICOSE',
                'parameter_name' => 'Glicose',
                'gender' => 'both',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => null,
                'reference_max' => 140.0,
                'unit' => 'mg/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => 'sem_jejum',
                'description' => 'Sem jejum',
                'source' => 'SBD',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 11. TSH - By age groups
            [
                'parameter_code' => 'TSH',
                'parameter_name' => 'TSH',
                'gender' => 'both',
                'age_min' => 18,
                'age_max' => null,
                'reference_min' => 0.40,
                'reference_max' => 4.00,
                'unit' => 'µUI/mL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => 'Adultos',
                'source' => 'SBEM',
                'laboratory_id' => null,
                'active' => true,
            ],
            [
                'parameter_code' => 'TSH',
                'parameter_name' => 'TSH',
                'gender' => 'both',
                'age_min' => 0,
                'age_max' => 17,
                'reference_min' => 0.70,
                'reference_max' => 5.70,
                'unit' => 'µUI/mL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => 'Crianças e adolescentes',
                'source' => 'SBEM',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 12. VITAMINA D - Categorical
            [
                'parameter_code' => 'VIT_D',
                'parameter_name' => 'Vitamina D',
                'gender' => 'both',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => null,
                'reference_max' => null,
                'unit' => 'ng/mL',
                'reference_type' => 'categorical',
                'reference_categories' => json_encode([
                    ['name' => 'Baixo', 'min' => null, 'max' => 20],
                    ['name' => 'Inadequado', 'min' => 20, 'max' => 30],
                    ['name' => 'Adequado', 'min' => 30, 'max' => 100],
                    ['name' => 'Alto', 'min' => 100, 'max' => null],
                ]),
                'condition' => null,
                'description' => null,
                'source' => 'Endocrine Society',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 13. VITAMINA B12 - Simple
            [
                'parameter_code' => 'VIT_B12',
                'parameter_name' => 'Vitamina B12',
                'gender' => 'both',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => 211.0,
                'reference_max' => 946.0,
                'unit' => 'pg/mL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => null,
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 14. HEMOGLOBINA - By gender
            [
                'parameter_code' => 'HB',
                'parameter_name' => 'Hemoglobina',
                'gender' => 'male',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => 13.0,
                'reference_max' => 17.0,
                'unit' => 'g/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => 'Homem',
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],
            [
                'parameter_code' => 'HB',
                'parameter_name' => 'Hemoglobina',
                'gender' => 'female',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => 12.0,
                'reference_max' => 16.0,
                'unit' => 'g/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => 'Mulher',
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],

            // 15. UREIA - Simple
            [
                'parameter_code' => 'UREIA',
                'parameter_name' => 'Ureia',
                'gender' => 'both',
                'age_min' => null,
                'age_max' => null,
                'reference_min' => 10.0,
                'reference_max' => 50.0,
                'unit' => 'mg/dL',
                'reference_type' => 'numeric',
                'reference_categories' => null,
                'condition' => null,
                'description' => null,
                'source' => 'SBPC',
                'laboratory_id' => null,
                'active' => true,
            ],
        ];

        foreach ($references as $reference) {
            StandardReferenceRange::firstOrCreate(
                [
                    'parameter_code' => $reference['parameter_code'],
                    'gender' => $reference['gender'],
                    'age_min' => $reference['age_min'],
                    'age_max' => $reference['age_max'],
                    'condition' => $reference['condition'],
                ],
                $reference
            );
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        StandardReferenceRange::whereIn('parameter_code', [
            'POTASSIO',
            'CREAT',
            'AC_URICO',
            'FERRO',
            'TEST_TOTAL',
            'COL_TOTAL',
            'LDL',
            'HDL',
            'TRIG',
            'GLICOSE',
            'TSH',
            'VIT_D',
            'VIT_B12',
            'HB',
            'UREIA',
        ])->delete();
    }
};
